#ifndef CAXCOMMAND_H
#define CAXCOMMAND_H

//////////////////////////////////////////////////
// key
//////////////////////////////////////////////////

#define		KEY_ACTION			"Action"
#define		KEY_ACTIVE_CHANNEL	"activeChannel"
#define		KEY_ACTS			"Acts"
#define		KEY_ADDR			"Addr"
#define		KEY_AL				"Al"
#define		KEY_ALBUM			"Album"
#define		KEY_ALBUM_ARTIST	"AlbumArtist"
#define		KEY_ALBUM_ID		"AlbumID"
#define		KEY_APP				"App"
#define		KEY_ART				"Art"
#define		KEY_ART_URL			"ArtUrl"
#define		KEY_ARTIST			"Artist"
#define		KEY_ARTIST_ID			"ArtistID"
#define		KEY_AS				"As"
#define		KEY_AUDIO_CD		"AudioCd"
#define		KEY_AUTO_JOIN		"Autojoin"
#define		KEY_AUTO_JOIN_ENABLED		"autoJoinEnabled"

#define		KEY_BIT_DEPTH		"BitDepth"
#define		KEY_BITRATE			"BitRate"
#define		KEY_BPS				"bps"
#define		KEY_BOT				"Bot"
#define		KEY_BOT1			"Bot1"

#define		KEY_CA_NAME			"caName"
#define		KEY_CANCEL			"Cancel"
#define		KEY_CAT_ORDER		"CatOrder"
#define		KEY_CATEGORY		"Cat"
#define		KEY_CD				"Cd"
#define		KEY_CDNUMBER		"CdNumber"
#define		KEY_CDTOTAL			"CdTotal"
#define		KEY_CDYEAR			"CdYear"
#define		KEY_CHANNEL			"Channel"
#define		KEY_CHANNELS			"Channels"
#define		KEY_CLEAR			"Clear"
#define		KEY_CLIENT_LIST		"ClientList"
#define		KEY_CMD0			"Cmd0"
#define		KEY_CMD1			"Cmd1"
#define		KEY_CMD2			"Cmd2"
#define		KEY_COMPOSER		"Composer"
#define		KEY_COUNT			"count"
#define		KEY_COVER_ART		"CoverArt"
#define		KEY_CURR_PLAY		"CurrPlay"

#define		KEY_DAB				"Dab"
#define		KEY_DESC			"Desc"
#define		KEY_DEV				"Dev"
#define		KEY_DEV_LIST		"DevList"
#define		KEY_DEV_LIST_UPDATE	"DevListUpdated"
#define		KEY_DELETE			"Delete"
#define		KEY_DIR_ONLY		"DirOnly"
#define		KEY_DIRS			"Dirs"
#define		KEY_DST				"Dst"
#define		KEY_DST_PATH		"DstPath"
#define		KEY_DURATION		"Duration"

#define		KEY_ENABLED			"enabled"
#define		KEY_ENABLE_CAP		"Enable"
#define		KEY_ETC_ORDER		"EtcOrder"
#define		KEY_EVENT_ID		"EventID"
#define		KEY_EXTENSION		"extension"

#define		KEY_FAVORITE		"favorite"
#define		KEY_FAVORITE_CAP		"Favorite"
#define		KEY_FILE			"File"
#define		KEY_FILES			"Files"
#define		KEY_FILTERS			"Filters"
#define		KEY_FM_RADIO		"FmRadio"
#define		KEY_FOLDER			"Folder"
#define		KEY_FORM			"Form"
#define		KEY_FORMATS			"Formats"
#define		KEY_FORMAT			"Format"
#define		KEY_FREE			"Free"
#define		KEY_FREQ			"Freq"
#define		KEY_FREQ_MAX		"FreqMax"
#define		KEY_FREQ_MIN		"FreqMin"
#define		KEY_FREQ_STEP		"FreqStep"


#define		KEY_GENRE			"Genre"
#define		KEY_GENRE_ID		"GenreID"
#define		KEY_GROUP_PLAY		"GroupPlay"
#define		KEY_GROUP_PLAY_STATUS	"groupPlayStatus"

#define		KEY_ICON			"Icon"
#define		KEY_ID_LOWER		"id"
#define		KEY_ID_UPPER		"ID"
#define		KEY_IDS				"IDs"
#define		KEY_INFO			"Info"
#define		KEY_IMAGE			"Image"
#define		KEY_IMAGE_URL		"ImageUrl"
#define		KEY_INDEX			"Index"
#define		KEY_INDEXES			"Indexes"
#define		KEY_INPUT			"Input"
#define		KEY_INPUTS			"Inputs"
#define		KEY_INPUT_SAMPLE_RATE	"InputSampleRate"
#define		KEY_IS_DEL_DB		"IsDelDB"
#define		KEY_ISERVICE		"IService"
#define		KEY_ITEM_TYPE		"ItemType"

#define		KEY_KEY				"Key"
#define		KEY_KEYWORD			"Str"

#define		KEY_LEFT			"Left"
#define		KEY_LIST			"List"
#define		KEY_LOCATION		"location"

#define		KEY_MAC				"Mac"
#define		KEY_MAC_ADDR		"macAddr"
#define		KEY_MENU			"Menu"
#define		KEY_MENU_DEPTH		"MenuDepth"
#define		KEY_MOOD			"Mood"
#define		KEY_MOVE			"Move"
#define		KEY_MQA				"MQA"
#define		KEY_MUTE_CAP		"Mute"
#define		KEY_MUTED			"muted"

#define		KEY_NAME_CAP		"Name"
#define		KEY_NAME			"name"
#define		KEY_NEXT			"Next"
#define		KEY_NEXT_URL		"NextUrl"
#define		KEY_NOW_PLAY		"NowPlaying"

#define		KEY_OK			"Ok"
#define		KEY_ORDER			"Order"
#define		KEY_OVERWRITE		"Overwrite"

#define		KEY_PAGE_CNT		"PageCnt"
#define		KEY_PASS			"Pass"
#define		KEY_PATH			"Path"
#define		KEY_PATHS			"Paths"
#define		KEY_PLAY			"Play"
#define		KEY_PLAY_PAUSE		"PlayPause"
#define		KEY_PLAY_STATE		"PlayState"
#define		KEY_PLAY_TIME		"PlayTime"
#define		KEY_PLS				"Pls"
#define		KEY_PLS_ID			"PlsID"
#define		KEY_POSITION		"Pos"
#define		KEY_PREV			"Prev"
#define		KEY_PROGRAM			"Program"
#define		KEY_PROGRESS		"Progress"

#define		KEY_QOBUZ_MENU		"QobuzMenu"

#define		KEY_RATING			"rating"
#define		KEY_RATING_CAP		"Rating"
#define		KEY_RECORD			"Record"
#define		KEY_RECORDABLE		"Recordable"
#define		KEY_REPEAT			"Repeat"
#define		KEY_RESULT			"Result"
#define		KEY_RIGHT			"Right"
#define		KEY_ROOT			"Root"

#define		KEY_SAMPLERATE		"samplerate"
#define		KEY_SAMPLERATE_CAP	"SampleRate"
#define		KEY_SAVE_AUTH		"SaveAuth"
#define		KEY_SCAN_DB			"ScanDB"
#define		KEY_SEARCH1			"Search1"
#define		KEY_SEARCH2			"Search2"
#define		KEY_SEEK			"Seek"
#define		KEY_SELF			"Self"
#define		KEY_SERVER			"Server"
#define		KEY_SETUP			"Setup"
#define		KEY_SITE			"Site"
#define		KEY_SIZE			"Size"
#define		KEY_SONG			"Song"
#define		KEY_SONG_FILES		"SongFiles"
#define		KEY_SONG_ORDER		"SongOrder"
#define		KEY_SOURCE			"Source"
#define		KEY_SQL				"Sql"
#define		KEY_SRC				"Src"
#define		KEY_SRC_PATH		"SrcPath"
#define		KEY_SRC_PATHS		"SrcPaths"
#define		KEY_START			"Start"
#define		KEY_STOP			"stop"
#define		KEY_SUB_DIR			"SubDir"
#define		KEY_SUBTITLE		"subtitle"
#define		KEY_SVC_TYPE		"SvcType"
#define		KEY_SWAP			"Swap"

#define		KEY_TASK			"Task"
#define		KEY_TASK_ID			"TaskID"
#define		KEY_TEMPO			"Tempo"
#define		KEY_TITLE			"title"
#define		KEY_TITLE_CAP		"Title"
#define		KEY_TIME			"time"
#define		KEY_TIME_CAP		"Time"
#define		KEY_TIME_STAMP		"TS"
#define		KEY_THUMB_URL		"ThumUrl"
#define		KEY_TRACK			"Track"
#define		KEY_TRACKS			"Tracks"
#define		KEY_TOP				"Top"
#define		KEY_TOTAL			"total"
#define		KEY_TOTAL_UPPER		"Total"
#define		KEY_TYPE			"Type"

#define		KEY_URL				"Url"
#define		KEY_USER			"User"

#define		KEY_VAL				"Val"
#define		KEY_VALUE			"Value"
#define		KEY_VALUES			"Values"
#define		KEY_VOLUME			"volume"
#define		KEY_VOLUME_CAP		"Volume"

#define		KEY_WHERE			"Where"
#define		KEY_WOL				"WOL"

#define		KEY_YEAR			"Year"
#define		KEY_YEARS			"Years"

//////////////////////////////////////////////////
// value
//////////////////////////////////////////////////

#define		VAL_ADD				"Add"
#define		VAL_AIRABLE			"Airable"
#define		VAL_ALBUM			"Album"
#define		VAL_ALL				"All"
#define		VAL_APP_INFO		"AppInfo"
#define		VAL_ARTIST			"Artist"
#define		VAL_AUDIO_CD		"AudioCd"
#define		VAL_AUTH			"Auth"

#define		VAL_BACK			"Back"
#define		VAL_BEST_SELLERS	"BestSellers"
#define		VAL_BOT				"Bot"
#define		VAL_BROWSER			"Browser"

#define		VAL_CATEGORY		"Cat"
#define		VAL_CHANNEL			"Channel"
#define		VAL_CLEAR			"Clear"
#define		VAL_COMPOSER		"Composer"
#define		VAL_CONVERT			"Convert"
#define		VAL_COPY			"Copy"
#define		VAL_COUNT			"Count"
#define		VAL_COVER_ART		"CoverArt"
#define		VAL_CREATE_FOLDER	"CreateFolder"
#define		VAL_CUR_SEC			"CurrSec"

#define		VAL_DAB_RADIO		"Dab"
#define		VAL_DEL				"Del"
#define		VAL_DESC			"Desc"
#define		VAL_DEV_LIST		"DevList"
#define		VAL_DISP			"Disp"

#define		VAL_EDITOR_PICKS	"EditorPicks"
#define		VAL_EJECT			"Eject"
#define		VAL_ENABLE			"Enable"
#define		VAL_ETC				"Etc"

#define		VAL_FAVORITE		"Favorite"
#define		VAL_FM_RADIO		"FmRadio"
#define		VAL_FOLDER			"Folder"

#define		VAL_GAIN_CLEAR		"GainClear"
#define		VAL_GAIN_SET		"GainSet"
#define		VAL_GENRE			"Genre"
#define		VAL_GROUP			"Group"
#define		VAL_GROUP_PLAY		"GroupPlay"

#define		VAL_ID_BEST_SELLERS		"best-sellers"
#define		VAL_ID_EDITOR_PICKS		"editor-picks"
#define		VAL_ID_LAST_CREATED		"last-created"
#define		VAL_ID_MOST_FEATURED	"most-featured"
#define		VAL_ID_MOST_STREAMED	"most-streamed"
#define		VAL_ID_NEW_RELEASES		"new-releases"
#define		VAL_ID_PRESS_AWARDS		"press-awards"
#define		VAL_IMAGE			"Image"
#define		VAL_INDEX			"Index"
#define		VAL_INFO			"Info"
#define		VAL_INPUT			"Input"

#define		VAL_JOIN			"Join"

#define		VAL_LAST_CREATED	"LastCreated"
#define		VAL_LIST			"List"
#define		VAL_LOGIN			"Login"

#define		VAL_MOOD			"Mood"
#define		VAL_MOST_FEATURED	"MostFeatured"
#define		VAL_MOST_STREAMED	"MostStreamd"
#define		VAL_MSG				"msg"
#define		VAL_MUSIC_DB		"MusicDB"
#define		VAL_MUTE			"MUTE"

#define		VAL_NEW				"New"
#define		VAL_NEW_RELEASES	"NewReleases"
#define		VAL_NEXT_URL		"NextUrl"

#define		VAL_OBSERVE			"Observe"

#define		VAL_PLAY			"Play"
#define		VAL_PLAYLIST		"Playlist"
#define		VAL_PLS				"Pls"
#define		VAL_POWER_OFF		"PowerOff"
#define		VAL_PRESS_AWARDS	"PressAward"

#define		VAL_QOBUZ			"Qobuz"
#define		VAL_QUERY			"Query"
#define		VAL_QUIT			"Quit"

#define		VAL_RECOMMEND		"Recommend"
#define		VAL_RECORD_LIST		"RecordList"
#define		VAL_REMOTE			"Remote"
#define		VAL_REMOVE_DB		"RemoveDB"
#define		VAL_RENAME			"Rename"
#define		VAL_REPLAY_GAIN		"ReplayGain"
#define		VAL_RESULT			"Result"
#define		VAL_RIP_INFO		"RipInfo"
#define		VAL_RIP				"Rip"
#define		VAL_ROOT			"Root"

#define		VAL_SCAN_DB			"ScanDB"
#define		VAL_SEARCH			"Search"
#define		VAL_SEEK			"Seek"
#define		VAL_SEEK_STOP		"SeekStop"
#define		VAL_SET				"Set"
#define		VAL_SET_ALBUM		"SetAlbum"
#define		VAL_SET_ART			"SetArt"
#define		VAL_SET_MUTE		"SetMute"
#define		VAL_SET_POSITION	"SetPos"
#define		VAL_SET_TAG			"SetTag"
#define		VAL_SET_VOLUME		"SetVol"
#define		VAL_SETUP			"Setup"
#define		VAL_SHUFFLE			"SHUFFLE"
#define		VAL_SKIP			"Skip"
#define		VAL_SONG			"Song"
#define		VAL_STOP			"Stop"
#define		VAL_SUCCESS			"success"

#define		VAL_TASK			"Task"
#define		VAL_TASKS			"Tasks"
#define		VAL_TASK_ID			"TaskID"
#define		VAL_TRACK			"Track"
#define		VAL_THUMB			"Thum"
#define		VAL_TITLE_CAP		"Title"
#define		VAL_TOTAL			"Total"
#define		VAL_TOTAL_SEC		"TotalSec"

#define		VAL_URL				"Url"
#define		VAL_URLS			"Urls"

#define		VAL_YEAR			"Year"


#endif // CAXCOMMAND_H
